services:
  postgres:
    build: .
    container_name: sql2git-demo-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sql2git_demo_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      #- ./dumps:/var/lib/postgresql/dumps

volumes:
  data:
  #dumps: